# Generated by Django 4.2.3 on 2023-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Admission_No', models.CharField(max_length=7)),
                ('Student_name', models.CharField(max_length=50)),
            ],
        ),
    ]
