# Generated by Django 4.2.3 on 2023-10-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_studentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='id',
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='Admission_No',
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
