# Generated by Django 4.2.3 on 2023-10-24 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_remove_studentdetails_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentdetails',
        ),
    ]
