# Generated by Django 4.2.3 on 2023-10-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_delete_studentdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentdetails',
            fields=[
                ('Admission_No', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Student_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
